// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXuTLuK-zQ7LLjymkuhz06isSYHZtWPwA',
    appId: '1:1046216357174:web:4ce32f9c512b099ed2af97',
    messagingSenderId: '1046216357174',
    projectId: 'expenditurebuddy-4d533',
    authDomain: 'expenditurebuddy-4d533.firebaseapp.com',
    storageBucket: 'expenditurebuddy-4d533.firebasestorage.app',
    measurementId: 'G-C47VE45ZYV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNI3LCdwTVStp7T42lGq-p4Ovg3tZzuDU',
    appId: '1:1046216357174:android:2ef869ffbedcf244d2af97',
    messagingSenderId: '1046216357174',
    projectId: 'expenditurebuddy-4d533',
    storageBucket: 'expenditurebuddy-4d533.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyjBf-sjRvQ-HR7_BXEoUcLo95u7i3uuI',
    appId: '1:1046216357174:ios:f5e3d208c8114ae2d2af97',
    messagingSenderId: '1046216357174',
    projectId: 'expenditurebuddy-4d533',
    storageBucket: 'expenditurebuddy-4d533.firebasestorage.app',
    iosClientId: '1046216357174-8d251r5ge7mu9at4h4eo3ralg7t9sict.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditurebuddy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyjBf-sjRvQ-HR7_BXEoUcLo95u7i3uuI',
    appId: '1:1046216357174:ios:f5e3d208c8114ae2d2af97',
    messagingSenderId: '1046216357174',
    projectId: 'expenditurebuddy-4d533',
    storageBucket: 'expenditurebuddy-4d533.firebasestorage.app',
    iosClientId: '1046216357174-8d251r5ge7mu9at4h4eo3ralg7t9sict.apps.googleusercontent.com',
    iosBundleId: 'com.example.expenditurebuddy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXuTLuK-zQ7LLjymkuhz06isSYHZtWPwA',
    appId: '1:1046216357174:web:f9ff4e496a05e2c0d2af97',
    messagingSenderId: '1046216357174',
    projectId: 'expenditurebuddy-4d533',
    authDomain: 'expenditurebuddy-4d533.firebaseapp.com',
    storageBucket: 'expenditurebuddy-4d533.firebasestorage.app',
    measurementId: 'G-NB0W68QXTG',
  );
}
